# Generated by Django 4.0.6 on 2022-08-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetails',
            name='nature_of_disposal',
        ),
        migrations.AlterField(
            model_name='casedetails',
            name='coram',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
