# Generated by Django 4.0.6 on 2022-08-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0002_remove_casepetitioner_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_to',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='action_notify_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_type',
            field=models.CharField(blank=True, choices=[('New Case Update', 'New Case Update'), ('Doc Deadline', 'Doc Deadline'), ('Hearing Update', 'Hearing Update'), ('Next Hearing', 'Next Hearing'), ('Hearing in 2 days', 'Hearing in 2 days')], max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='TrackCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_status', models.CharField(blank=True, choices=[('Case Dates Updated', 'Case Dates Updated'), ('Doc Updated', 'Doc Updated')], max_length=150, null=True)),
                ('action_description', models.CharField(blank=True, max_length=250, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('action_taken_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
        ),
    ]
