# Generated by Django 4.1 on 2022-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cnr_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='filling_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
