# Generated by Django 4.0.6 on 2022-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_remove_casedetails_nature_of_disposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='case_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPOSED', 'Disposed')], max_length=50),
        ),
    ]
