# Generated by Django 4.0.6 on 2022-08-04 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0005_advocate_judge'),
        ('petitionFiling', '0007_rename_central_rule_act_act_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0003_alter_casedetails_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnr_number', models.IntegerField(unique=True)),
                ('case_type', models.CharField(max_length=50, null=True)),
                ('filling_number', models.IntegerField()),
                ('registration_number', models.DateField(null=True)),
                ('act', models.ManyToManyField(blank=True, null=True, to='petitionFiling.act')),
                ('advocate', models.ManyToManyField(blank=True, null=True, to='permuser.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_of_case', models.CharField(blank=True, max_length=50)),
                ('coram', models.CharField(blank=True, default='', max_length=50)),
                ('bench', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('judicial', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('causelist_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('latest_hearing', models.DateField(blank=True, default='', null=True)),
                ('decision_date', models.DateField(blank=True, default='', null=True)),
                ('case_status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPOSED', 'Disposed')], max_length=50)),
                ('next_date', models.DateField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.IntegerField(blank=True, default=0, null=True)),
                ('recieving_date', models.DateField(blank=True, default=0, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('advocate', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='permuser.advocate')),
                ('filed_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_list_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hearing_date', models.DateField(blank=True, default=0, null=True)),
                ('purpose_of_hearing', models.CharField(blank=True, choices=[], default='', max_length=50, null=True)),
                ('judge', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='permuser.judge')),
            ],
        ),
        migrations.CreateModel(
            name='IADetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_number', models.CharField(blank=True, max_length=50, null=True)),
                ('filing_date', models.DateField(blank=True, default=0, null=True)),
                ('next_date', models.DateField(blank=True, default=0, null=True)),
                ('ia_status', models.CharField(blank=True, choices=[], default='', max_length=50, null=True)),
                ('party', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrutiny_date', models.DateField(blank=True, default=0, null=True)),
                ('objection', models.CharField(blank=True, max_length=500, null=True)),
                ('compliance_date', models.DateField(blank=True, default=0, null=True)),
                ('reciept_date', models.DateField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, default=0, null=True)),
                ('judge', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='permuser.judge')),
            ],
        ),
        migrations.DeleteModel(
            name='CaseDetails',
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.casestatus'),
        ),
        migrations.AddField(
            model_name='case',
            name='document',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.documentdetails'),
        ),
        migrations.AddField(
            model_name='case',
            name='history',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.history'),
        ),
        migrations.AddField(
            model_name='case',
            name='ia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.iadetails'),
        ),
        migrations.AddField(
            model_name='case',
            name='objection',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.objection'),
        ),
        migrations.AddField(
            model_name='case',
            name='order',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='case.order'),
        ),
        migrations.AddField(
            model_name='case',
            name='petitioner',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.petitioner'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondent',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.respondent'),
        ),
    ]
