# Generated by Django 4.1 on 2022-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_case_status_case_person_involved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetails',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
