# Generated by Django 4.0.6 on 2022-08-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_remove_case_document_case_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_status',
            new_name='case_status_details',
        ),
    ]
