# Generated by Django 4.1 on 2022-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_remove_history_cause_list_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Writ', 'Writ'), ('Contempt', 'Contempt'), ('Civil', 'Civil')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='judge',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
