# Generated by Django 4.1 on 2022-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_case_bench_case_causelist_name_case_coram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH-COURT', 'High Court'), ('DISTRICT_COURT', 'District Court'), ('LOWER COURT', 'Lower Court')], max_length=50, null=True),
        ),
    ]
