# Generated by Django 4.0.6 on 2022-08-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_rename_case_status_case_case_status_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status_details',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_status_details', to='case.casestatus'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('mail_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('web_description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_viewed_in_mail', models.BooleanField(blank=True, default=False, null=True)),
                ('is_viewed_in_web', models.BooleanField(blank=True, default=False, null=True)),
                ('case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_notifications', to='case.case')),
            ],
        ),
    ]
