# Generated by Django 4.1 on 2022-08-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_case_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disposed', 'Disposed')], max_length=50, null=True),
        ),
    ]
