# Generated by Django 4.1 on 2022-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_remove_notification_case_notification_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='case_title',
        ),
    ]
