# Generated by Django 4.1 on 2022-08-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_notification_action_location_alter_case_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='case',
        ),
        migrations.AddField(
            model_name='notification',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_notifications', to='case.case'),
        ),
    ]
