# Generated by Django 4.0.6 on 2022-08-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0009_remove_petition_act_remove_petition_petitioner_and_more'),
        ('case', '0008_alter_case_case_type_alter_case_cnr_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='act',
        ),
        migrations.RemoveField(
            model_name='case',
            name='advocate',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_status_details',
        ),
        migrations.RemoveField(
            model_name='case',
            name='document',
        ),
        migrations.RemoveField(
            model_name='case',
            name='history',
        ),
        migrations.RemoveField(
            model_name='case',
            name='ia',
        ),
        migrations.RemoveField(
            model_name='case',
            name='objection',
        ),
        migrations.RemoveField(
            model_name='case',
            name='order',
        ),
        migrations.RemoveField(
            model_name='case',
            name='petitioner',
        ),
        migrations.RemoveField(
            model_name='case',
            name='respondent',
        ),
        migrations.AddField(
            model_name='casestatus',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_status', to='case.case'),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_document', to='case.case'),
        ),
        migrations.AddField(
            model_name='history',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='case.case'),
        ),
        migrations.AddField(
            model_name='iadetails',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_ia_details', to='case.case'),
        ),
        migrations.AddField(
            model_name='objection',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_objection', to='case.case'),
        ),
        migrations.AddField(
            model_name='order',
            name='case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_order', to='case.case'),
        ),
        migrations.CreateModel(
            name='CaseRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_father', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_address', models.TextField(blank=True, max_length=200, null=True)),
                ('respondent_country', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_city', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_email', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_respondent', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='CasePetitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('Arbitration Petition', 'Arbitration Petition'), ('Civil (Appeal) Petition', 'Civil (Appeal) Petition'), ('Contempt Petition (Civil)', 'Contempt Petition (Civil)'), ('Contempt Petition (Criminal)', 'Contempt Petition (Criminal)'), ('Criminal Appeal Petition', 'Criminal Appeal Petition'), ('Election Petition', 'Election Petition'), ('Original Suit', 'Original Suit'), ('Petition for Special Leave to Appeal', 'Petition for Special Leave to Appeal'), ('Transferred Case Petition', 'Transferred Case Petition'), ('Writ Petition', 'Writ Petition'), ('Review Petition', 'Review Petition'), ('Curative Petition', 'Curative Petition')], default='', max_length=50, null=True)),
                ('petitioner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_age', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_state', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('petitioner_country', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_mobile', models.IntegerField(blank=True, null=True)),
                ('petitioner_department', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_city', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_email', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_pin', models.IntegerField(blank=True, null=True)),
                ('petitioner_district', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_total_petition', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='case_petitioner', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(blank=True, max_length=150, null=True)),
                ('act_rule', models.CharField(blank=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, max_length=450, null=True)),
                ('rule_no', models.IntegerField(blank=True, null=True)),
                ('act_belong_to', models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('STATE', 'State')], max_length=50, null=True)),
                ('case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_act', to='case.case')),
                ('petition', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_petitioner', to='petitionFiling.petition')),
            ],
        ),
    ]
