# Generated by Django 4.1 on 2022-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_remove_notification_case_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='advocateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('age', models.IntegerField()),
                ('avg_resolvetime', models.IntegerField()),
                ('activecases', models.ImageField(upload_to='')),
            ],
        ),
    ]
