# Generated by Django 4.0.6 on 2022-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_remove_casepetitioner_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='document',
        ),
        migrations.AddField(
            model_name='case',
            name='document',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='case_document', to='case.documentdetails'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='history',
        ),
        migrations.AddField(
            model_name='case',
            name='history',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='case_history', to='case.history'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='ia',
        ),
        migrations.AddField(
            model_name='case',
            name='ia',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='ia_details', to='case.iadetails'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='objection',
        ),
        migrations.AddField(
            model_name='case',
            name='objection',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='case_objection', to='case.objection'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='order',
        ),
        migrations.AddField(
            model_name='case',
            name='order',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='case_order', to='case.order'),
        ),
    ]
