# Generated by Django 4.1 on 2022-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, choices=[('Writ', 'Writ'), ('Contempt', 'Contempt'), ('Civil', 'Civil')], default='', max_length=500, null=True)),
                ('case_category', models.CharField(blank=True, choices=[('Writ', 'Writ'), ('Contempt', 'Contempt'), ('Civil', 'Civil')], default='', max_length=500, null=True)),
                ('special_category', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('court', models.CharField(blank=True, choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH-COURT', 'High Court'), ('DISTRICT_COURT', 'District Court'), ('LOWER COURT', 'Lower Court')], max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('act', models.ManyToManyField(blank=True, null=True, related_name='petition_act', to='permuser.act')),
                ('petitioner', models.ManyToManyField(blank=True, null=True, related_name='petition_petitioner', to='permuser.petitioner')),
                ('respondent', models.ManyToManyField(blank=True, null=True, related_name='petition_respondent', to='permuser.respondent')),
            ],
        ),
    ]
