# Generated by Django 4.0.6 on 2022-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('bench', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=50)),
                ('special_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Petitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(max_length=50)),
                ('petitioner_state', models.CharField(max_length=50)),
                ('petitioner_address', models.CharField(max_length=200)),
                ('petitioner_country', models.CharField(max_length=50)),
                ('petitioner_mobile', models.IntegerField()),
                ('petitioner_department', models.CharField(max_length=50)),
                ('petitioner_city', models.CharField(max_length=50)),
                ('petitioner_email', models.CharField(max_length=50)),
                ('petitioner_pin', models.IntegerField(max_length=6)),
                ('petitioner_district', models.CharField(max_length=50)),
                ('petitioner_total_petition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Responded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=50)),
                ('respondent_relation', models.CharField(max_length=50)),
                ('respondent_father_husband', models.CharField(max_length=50)),
                ('respondent_gender', models.CharField(max_length=50)),
                ('respondent_address', models.TextField(max_length=200)),
                ('respondent_country', models.CharField(max_length=50)),
            ],
        ),
    ]
