# Generated by Django 4.0.6 on 2022-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(blank=True, max_length=150, null=True)),
                ('central_rule', models.CharField(blank=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, max_length=450, null=True)),
                ('rule_no', models.IntegerField(blank=True, null=True)),
                ('act_belong_to', models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('STATE', 'State')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_number', models.IntegerField(blank=True, null=True)),
                ('advocate_year', models.IntegerField(blank=True, null=True)),
                ('advocate_mobile', models.IntegerField(blank=True, null=True)),
                ('advocate_email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_type', models.CharField(blank=True, choices=[('PETITIONER_ADVOCATE', 'Petitioner Advocate'), ('RESPONDENT_ADVOCATE', 'Respondent Advocate')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_father', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_address', models.TextField(blank=True, max_length=200, null=True)),
                ('respondent_country', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_city', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Responded',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='bench',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='special_type',
        ),
        migrations.AddField(
            model_name='petition',
            name='case_category',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='special_category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petitioner',
            name='petitioner_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petitioner',
            name='petitioner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='case_type',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='court',
            field=models.CharField(blank=True, choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH-COURT', 'High Court'), ('DISTRICT_COURT', 'District Court'), ('LOWER COURT', 'Lower Court')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_total_petition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_type',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, null=True),
        ),
    ]
