# Generated by Django 4.0.6 on 2022-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='court',
            field=models.CharField(choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH-COURT', 'High Court'), ('DISTRICT_COURT', 'District Court')], max_length=50),
        ),
    ]
