# Generated by Django 3.1.5 on 2022-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0002_act_advocate_respondent_delete_responded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='petition',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.Petition'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='petition',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.Petition'),
        ),
        migrations.AddField(
            model_name='petitioner',
            name='petition',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.Petition'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='petition',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.Petition'),
        ),
        migrations.AlterField(
            model_name='act',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
