# Generated by Django 4.1 on 2022-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0003_alter_petition_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='case_category',
            field=models.CharField(blank=True, choices=[('Writ', 'Writ'), ('Contempt', 'Contempt'), ('Civil', 'Civil')], default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Writ', 'Writ'), ('Contempt', 'Contempt'), ('Civil', 'Civil')], default='', max_length=500, null=True),
        ),
    ]
