# Generated by Django 4.0.6 on 2022-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0003_auto_20220803_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='petitioner',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='petition',
        ),
        migrations.AddField(
            model_name='petition',
            name='act',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.act'),
        ),
        migrations.AddField(
            model_name='petition',
            name='advocate',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.advocate'),
        ),
        migrations.AddField(
            model_name='petition',
            name='petitioner',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.petitioner'),
        ),
        migrations.AddField(
            model_name='petition',
            name='respondent',
            field=models.ManyToManyField(blank=True, null=True, to='petitionFiling.respondent'),
        ),
        migrations.AlterField(
            model_name='act',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petitioner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
