# Generated by Django 4.0.6 on 2022-08-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0002_alter_petition_court'),
        ('petitionFiling', '0004_remove_act_petition_remove_advocate_petition_and_more'),
    ]

    operations = [
    ]
