# Generated by Django 4.0.6 on 2022-08-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0005_merge_20220803_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='court',
            field=models.CharField(blank=True, choices=[('SUPREME_COURT', 'Supreme Court'), ('HIGH-COURT', 'High Court'), ('DISTRICT_COURT', 'District Court'), ('LOWER COURT', 'Lower Court')], max_length=50, null=True),
        ),
    ]
