# Generated by Django 4.0.6 on 2022-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0006_alter_petition_court'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='central_rule',
            new_name='act_rule',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='advocate',
        ),
        migrations.AddField(
            model_name='petition',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Advocate',
        ),
    ]
