# Generated by Django 4.0.6 on 2022-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitionFiling', '0010_remove_petitioner_petition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='petition_file_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
