# Generated by Django 4.0.6 on 2022-07-31 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.TextField(blank=True, max_length=50, null=True)),
                ('organization_email', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_upload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.TextField(blank=True, max_length=50, null=True)),
                ('employee_email', models.CharField(max_length=200, unique=True)),
                ('employee_mobile', models.CharField(max_length=200, unique=True)),
                ('employee_password', models.CharField(max_length=200, unique=True)),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='permuser.organizationmodel')),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_permission', to='permuser.userpermission')),
            ],
        ),
    ]
