# Generated by Django 4.0.6 on 2022-08-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='organization_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_permission', to='permuser.userpermission'),
        ),
        migrations.DeleteModel(
            name='OrganizationModel',
        ),
    ]
