# Generated by Django 4.1 on 2022-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0002_remove_advocate_advocate_number_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.ManyToManyField(blank=True, null=True, to='permuser.tags'),
        ),
    ]
