# Generated by Django 4.1 on 2022-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0003_customuser_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioner',
            name='petitioner_type',
            field=models.CharField(blank=True, choices=[('Writ Petition', 'Writ Petition'), ('Civil (Appeal) Petition', 'Civil (Appeal) Petition'), ('Contempt Petition (Civil)', 'Contempt Petition (Civil)'), ('Contempt Petition (Criminal)', 'Contempt Petition (Criminal)'), ('Review Petition', 'Review Petition')], default='', max_length=50, null=True),
        ),
    ]
