# Generated by Django 4.0.6 on 2022-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0004_alter_employeemodel_id_alter_userpermission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_number', models.IntegerField(blank=True, null=True)),
                ('advocate_year', models.IntegerField(blank=True, null=True)),
                ('advocate_mobile', models.IntegerField(blank=True, null=True)),
                ('advocate_email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_type', models.CharField(blank=True, choices=[('PETITIONER_ADVOCATE', 'Petitioner Advocate'), ('RESPONDENT_ADVOCATE', 'Respondent Advocate')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_number', models.IntegerField(blank=True, null=True)),
                ('advocate_year', models.IntegerField(blank=True, null=True)),
                ('advocate_mobile', models.IntegerField(blank=True, null=True)),
                ('advocate_email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate_type', models.CharField(blank=True, choices=[('PETITIONER_ADVOCATE', 'Petitioner Advocate'), ('RESPONDENT_ADVOCATE', 'Respondent Advocate')], max_length=50, null=True)),
            ],
        ),
    ]
