<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-06 19:14
=======
# Generated by Django 4.1 on 2022-08-08 17:51
>>>>>>> rahul

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0005_advocate_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(blank=True, max_length=150, null=True)),
                ('act_rule', models.CharField(blank=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, max_length=450, null=True)),
                ('rule_no', models.IntegerField(blank=True, null=True)),
                ('act_belong_to', models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('STATE', 'State')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInvolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('person_mobile', models.IntegerField(blank=True, null=True)),
                ('person_email', models.CharField(blank=True, max_length=50, null=True)),
                ('person_age', models.CharField(blank=True, max_length=50, null=True)),
                ('person_address', models.CharField(blank=True, max_length=200, null=True)),
                ('person_state', models.CharField(blank=True, max_length=50, null=True)),
                ('person_city', models.CharField(blank=True, max_length=50, null=True)),
                ('person_pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner_type', models.CharField(blank=True, choices=[('Arbitration Petition', 'Arbitration Petition'), ('Civil (Appeal) Petition', 'Civil (Appeal) Petition'), ('Contempt Petition (Civil)', 'Contempt Petition (Civil)'), ('Contempt Petition (Criminal)', 'Contempt Petition (Criminal)'), ('Criminal Appeal Petition', 'Criminal Appeal Petition'), ('Election Petition', 'Election Petition'), ('Original Suit', 'Original Suit'), ('Petition for Special Leave to Appeal', 'Petition for Special Leave to Appeal'), ('Transferred Case Petition', 'Transferred Case Petition'), ('Writ Petition', 'Writ Petition'), ('Review Petition', 'Review Petition'), ('Curative Petition', 'Curative Petition')], default='', max_length=50, null=True)),
                ('petitioner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_age', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_state', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('petitioner_country', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_mobile', models.IntegerField(blank=True, null=True)),
                ('petitioner_department', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_city', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_email', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_pin', models.IntegerField(blank=True, null=True)),
                ('petitioner_district', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_total_petition', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_father', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_address', models.TextField(blank=True, max_length=200, null=True)),
                ('respondent_country', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_city', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='advocate_email_id',
            new_name='judge_email_id',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='advocate_mobile',
            new_name='judge_mobile',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='advocate_name',
            new_name='judge_name',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='advocate_number',
            new_name='judge_number',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='advocate_year',
            new_name='judge_year',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='advocate_type',
        ),
    ]
