# Generated by Django 4.1 on 2022-08-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permuser', '0006_act_personinvolved_petitioner_respondent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondent',
            old_name='petitioner_city',
            new_name='respondent_city',
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='petitioner_email',
            new_name='respondent_email',
        ),
    ]
